### ISSUE TITLE
Update README with goal of website

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/waku.guide#10]
Goal:

Documentation published on this website are meant for dApp developers, CTO, product owners that are interested in a high level overview of Waku and Waku protocols.

When a reader comes here, they should understand:

- How Waku or a given protocol is going to help their product
- How they should design their product to use Waku, what protocol they should select
- Where to go to to start writing code (e.g js.waku.org)
- Where to go to to read more about the protocol (e.g. RFCs or [vac.dev/rln-relay](https://vac.dev/rln-relay))

**Comment by LordGhostX** [comment]
The latest version of <https://dev.waku.guide/> addresses the majority of these issues. There is no need to duplicate the content of the docs in the README; instead, we can reserve it for providing instructions on running the platform locally and making contributions.

**Comment by fryorcraken** [comment]
sounds good
