### ISSUE TITLE
Add section for Waku Message

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/waku.guide#12]
Would be good to add a section explaining the Waku message format

**Comment by LordGhostX** [comment]
Do you think this page solved this? https://dev.waku.guide/overview/concepts/protocols#waku-message

**Comment by fryorcraken** [comment]
I think we could extend the section a bit more and list the following attributes from the messages with an explanation and reference to more docs:
- content topics
- paylaod
- meta 
- timestamp
- ephemeral
