### ISSUE TITLE
Change content topic recommendation

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/waku.guide#55]
## Problem

Current content topic recommendation does not include privacy minded use cases.

As per https://rfc.vac.dev/spec/23/#content-topic-naming-recommendations the `content-topic-name` can be used for privacy guarantees.
We currently only suggest to use it for _feature_ purpose.

## Solution

Do mention:
- privacy concerns in selecting a content topic
- k-anonymity and what guarantees Waku gives or does not give you
- Using one content topics for the full app and using protocol buffer message format to allow functionality switch

**Comment by fryorcraken** [comment]
@jm-clius Do we want to formalize some strategy around this such as the hashing of some PII and usage of first bytes (_ a la Status_)?

**Comment by jm-clius** [comment]
We should mention privacy implications when selecting content topics, yes, especially its use in filtering in both `store` and `filter` protocols. Perhaps we will need a more rigorous naming strategy for the public Waku network, but having explained the risks I wouldn't overdefine a strategy right now. We could give some recommendations re hashing PII and sharing content topics between smaller broadcast groups within an app to increase k-anonymity (somewhat similar to what Status does by using the first bytes)

**Comment by LordGhostX** [comment]
I added "Naming Considerations" section to the content topics page: https://waku-guide-git-docs-reorg-logosdao.vercel.app/getting-started/concepts/content-topics#naming-considerations.

Do you think it's good enough?

**Comment by fryorcraken** [comment]
Happy to close this issue once https://github.com/waku-org/waku.guide/pull/58#discussion_r1213800304 is tackled.
